version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - sam build
      - sam package --output-template-file myoutputtemplate.yaml --s3-bucket sam-java-codebuild-codepipeline
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - myoutputtemplate.yaml
